GREETING_COMMAND_CONST = 'Hi'
RANDOM_NUMBER_COMMAND_CONST = 'GetRandom'
SHUTDOWN_COMMAND_CONST = 'Shutdown'

GREETING_OUTPUT_CONST = 'Hi'
SHUTDOWN_OUTPUT_CONST = 'Goodbye'
ERROR_OUTPUT_CONST = 'Command not supported'
